name: Update README with Daily Fortune

on: workflow_dispatch

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Daily Fortune
        id: fortune
        run: |
          FORTUNE=$(curl -s "https://zenquotes.io/api/random" | jq -r '.[0].q + " -" + .[0].a')
          echo "::set-output name=message::$FORTUNE"

      - name: Update README
        run: |
          sed -i "/<!-- FORTUNE_START -->/,/<!-- FORTUNE_END -->/c\<!-- FORTUNE_START -->\n## Daily Fortune\n\n> \"${{ steps.fortune.outputs.message }}\"\n\n*(Updated on $(date "+%Y-%m-%d"))*\n<!-- FORTUNE_END -->" README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with daily fortune"
          git push

